create table public.tbtempo_libraries (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  revision bigint not null default 1 check (revision > 0),
  device_id text not null check (char_length(device_id) between 1 and 200),
  updated_at timestamptz not null default now()
);

create table public.tbtempo_library_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  source_revision bigint not null check (source_revision > 0),
  device_id text not null check (char_length(device_id) between 1 and 200),
  reason text not null check (char_length(reason) between 1 and 100),
  created_at timestamptz not null default now()
);

create index tbtempo_library_snapshots_user_created_idx
  on public.tbtempo_library_snapshots (user_id, created_at desc);

alter table public.tbtempo_libraries enable row level security;
alter table public.tbtempo_library_snapshots enable row level security;

revoke all on table public.tbtempo_libraries from anon, authenticated;
revoke all on table public.tbtempo_library_snapshots from anon, authenticated;
revoke all on sequence public.tbtempo_library_snapshots_id_seq from anon, authenticated;

grant select, insert, update on table public.tbtempo_libraries to authenticated;
grant select, insert, delete on table public.tbtempo_library_snapshots to authenticated;
grant usage, select on sequence public.tbtempo_library_snapshots_id_seq to authenticated;

create policy "Users can read their TB Tempo library"
  on public.tbtempo_libraries for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their TB Tempo library"
  on public.tbtempo_libraries for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their TB Tempo library"
  on public.tbtempo_libraries for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can read their TB Tempo history"
  on public.tbtempo_library_snapshots for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their TB Tempo history"
  on public.tbtempo_library_snapshots for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can prune their TB Tempo history"
  on public.tbtempo_library_snapshots for delete
  to authenticated
  using ((select auth.uid()) = user_id);
